<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TagsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        DB::table('tags')->insert([
            [
                'nama_tag' => 'pantai',
                'tag_seo' => 'pantai',
                'count' => 7,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Ekonomi',
                'tag_seo' => 'ekonomi',
                'count' => 7,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Hiburan',
                'tag_seo' => 'hiburan',
                'count' => 16,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Teknologi',
                'tag_seo' => 'teknologi',
                'count' => 8,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Metropolitan',
                'tag_seo' => 'metropolitan',
                'count' => 29,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Nasional',
                'tag_seo' => 'nasional',
                'count' => 38,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 14,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Olahraga',
                'tag_seo' => 'olahraga',
                'count' => 10,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Kuliner',
                'tag_seo' => 'kuliner',
                'count' => 17,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'seni-budaya',
                'tag_seo' => 'seni-budaya',
                'count' => 4,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Sekitar Kita',
                'tag_seo' => 'sekitar-kita',
                'count' => 9,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Wisata',
                'tag_seo' => 'wisata',
                'count' => 4,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Hukum',
                'tag_seo' => 'hukum',
                'count' => 13,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Musik',
                'tag_seo' => 'musik',
                'count' => 11,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Internasional',
                'tag_seo' => 'internasional',
                'count' => 22,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Bola',
                'tag_seo' => 'bola',
                'count' => 19,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'tokoh',
                'tag_seo' => 'tokoh',
                'count' => 0,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'pemerintahan',
                'tag_seo' => 'publish',
                'count' => 0,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'kampungtulangbawang',
                'tag_seo' => 'kampungtulangbawang',
                'count' => 0,
                'instansi_id' => 17,
            ],
            [
                'nama_tag' => 'umum',
                'tag_seo' => 'umum',
                'count' => 0,
                'instansi_id' => 37,
            ],
            [
                'nama_tag' => 'LAIN-LAIN',
                'tag_seo' => 'lain-lain',
                'count' => 0,
                'instansi_id' => 1,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 33,
            ],
            [
                'nama_tag' => 'DAERAH',
                'tag_seo' => 'daerah',
                'count' => 0,
                'instansi_id' => 32,
            ],
            [
                'nama_tag' => 'TulangBawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 43,
            ],
            [
                'nama_tag' => 'Ekonomi',
                'tag_seo' => 'ekonomi',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 10,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 41,
            ],
            [
                'nama_tag' => 'PEREKONOMIAN',
                'tag_seo' => 'perekonomian',
                'count' => 0,
                'instansi_id' => 6,
            ],
            [
                'nama_tag' => 'PELAYANAN PUBLIK',
                'tag_seo' => 'pelayanan-publik',
                'count' => 0,
                'instansi_id' => 49,
            ],
            [
                'nama_tag' => 'KEARSIPAN',
                'tag_seo' => 'kearsipan',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'bappedalitbangumum',
                'tag_seo' => 'bappedalitbangumum',
                'count' => 0,
                'instansi_id' => 32,
            ],
            [
                'nama_tag' => 'tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 2,
            ],
            [
                'nama_tag' => 'TULANGBAWANG',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 39,
            ],
            [
                'nama_tag' => 'Tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 11,
            ],
            [
                'nama_tag' => 'tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 19,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'Disparbudtuba',
                'tag_seo' => 'disparbudtuba',
                'count' => 0,
                'instansi_id' => 43,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'Budaya',
                'tag_seo' => 'budaya',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'PELAYANAN',
                'tag_seo' => 'pelayanan',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'tulangbawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 2,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 2,
            ],
            [
                'nama_tag' => 'Bagian hukum',
                'tag_seo' => 'bagian-hukum',
                'count' => 0,
                'instansi_id' => 36,
            ],
            [
                'nama_tag' => 'RSUD',
                'tag_seo' => 'rsud',
                'count' => 0,
                'instansi_id' => 47,
            ],
            [
                'nama_tag' => 'Perempuan dan Anak',
                'tag_seo' => 'perempuan-dan-anak',
                'count' => 0,
                'instansi_id' => 41,
            ],
            [
                'nama_tag' => 'KESSOS',
                'tag_seo' => 'kessos',
                'count' => 0,
                'instansi_id' => 25,
            ],
            [
                'nama_tag' => 'Bmw, Bergerak Melayani Warga, Tulang Bawang',
                'tag_seo' => 'bmw-bergerak-melayani-warga-tulang-bawang',
                'count' => 0,
                'instansi_id' => 8,
            ],
            [
                'nama_tag' => 'SOSIALISASI GEMAR MEMBACA',
                'tag_seo' => 'sosialisasi-gemar-membaca',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'BUPATI',
                'tag_seo' => 'bupati',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'Prestasi',
                'tag_seo' => 'prestasi',
                'count' => 0,
                'instansi_id' => 30,
            ],
            [
                'nama_tag' => 'PNS',
                'tag_seo' => 'pns',
                'count' => 0,
                'instansi_id' => 30,
            ],
            [
                'nama_tag' => 'aplikasi',
                'tag_seo' => 'aplikasi',
                'count' => 0,
                'instansi_id' => 45,
            ],
            [
                'nama_tag' => 'DISDUKCAPIL TULANG BAWANG',
                'tag_seo' => 'disdukcapil-tulang-bawang',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'Daftar Jenis Perizinan',
                'tag_seo' => 'daftar-jenis-perizinan',
                'count' => 0,
                'instansi_id' => 18,
            ],
            [
                'nama_tag' => 'UMUM',
                'tag_seo' => 'umum',
                'count' => 0,
                'instansi_id' => 47,
            ],
            [
                'nama_tag' => 'visi dan misi',
                'tag_seo' => 'visi-dan-misi',
                'count' => 0,
                'instansi_id' => 40,
            ],
            [
                'nama_tag' => 'PEMERINTAHAN',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 47,
            ],
            [
                'nama_tag' => 'PELAYANAN',
                'tag_seo' => 'pelayanan',
                'count' => 0,
                'instansi_id' => 47,
            ],
            [
                'nama_tag' => 'Standar Pelayanan',
                'tag_seo' => 'standar-pelayanan',
                'count' => 0,
                'instansi_id' => 18,
            ],
            [
                'nama_tag' => 'PEMERINTAHAN',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'SAT POL PP TULANG BAWANG',
                'tag_seo' => 'sat-pol-pp-tulang-bawang',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'SAT POL PP LAMPUNG',
                'tag_seo' => 'sat-pol-pp-lampung',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'PENYULUHAN',
                'tag_seo' => 'penyuluhan',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'PENYULUHAN',
                'tag_seo' => 'penyuluhan',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'MAL PELAYANAN PUBLIK',
                'tag_seo' => 'mal-pelayanan-publik',
                'count' => 0,
                'instansi_id' => 18,
            ],
            [
                'nama_tag' => 'lingkungan hidup',
                'tag_seo' => 'lingkungan-hidup',
                'count' => 0,
                'instansi_id' => 11,
            ],
            [
                'nama_tag' => 'Pemerintahan',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 31,
            ],
            [
                'nama_tag' => 'Bantuan sosial',
                'tag_seo' => 'bantuan-sosial',
                'count' => 0,
                'instansi_id' => 31,
            ],
            [
                'nama_tag' => 'Keagamaan',
                'tag_seo' => 'keagamaan',
                'count' => 0,
                'instansi_id' => 31,
            ],
            [
                'nama_tag' => 'LPSE',
                'tag_seo' => 'lpse',
                'count' => 0,
                'instansi_id' => 50,
            ],
            [
                'nama_tag' => 'PENGUMUMAN',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'PERLOMBAAN',
                'tag_seo' => 'perlombaan',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'PENGGERAKAN',
                'tag_seo' => 'penggerakan',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'SOSIALISASI',
                'tag_seo' => 'sosialisasi',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'PELAYANAN',
                'tag_seo' => 'pelayanan',
                'count' => 0,
                'instansi_id' => 20,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 21,
            ],
            [
                'nama_tag' => 'ALURSOP',
                'tag_seo' => 'alursop',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'PENGUMUMAN',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'Pengumuman',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 36,
            ],
            [
                'nama_tag' => 'PENGUMUMAN',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 31,
            ],
            [
                'nama_tag' => 'PELAYANAN',
                'tag_seo' => 'pelayanan',
                'count' => 0,
                'instansi_id' => 23,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 38,
            ],
            [
                'nama_tag' => 'Pendidikan',
                'tag_seo' => 'pendidikan',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'Pariwisata',
                'tag_seo' => 'pariwisata',
                'count' => 0,
                'instansi_id' => 9,
            ],
            [
                'nama_tag' => 'TRANSFORMASI PERPUSTAKAAN BERBASIS INKLUSI SOSIAL',
                'tag_seo' => 'transformasi-perpustakaan-berbasis-inklusi-sosial',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'SDM',
                'tag_seo' => 'sdm',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => '#bmwtulangbawang',
                'tag_seo' => 'bmwtulangbawang',
                'count' => 0,
                'instansi_id' => 4,
            ],
            [
                'nama_tag' => 'Pembinaan dan Advokasi',
                'tag_seo' => 'pembinaan-dan-advokasi',
                'count' => 0,
                'instansi_id' => 50,
            ],
            [
                'nama_tag' => 'LOMBA PIDATO BAHASA LAMPUNG TINGKAT SMP SE PROVINSI LAMPUNG',
                'tag_seo' => 'lomba-pidato-bahasa-lampung-tingkat-smp-se-provinsi-lampung',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'Dinas Pertanian Tulang Bawang',
                'tag_seo' => 'dinas-pertanian-tulang-bawang',
                'count' => 0,
                'instansi_id' => 5,
            ],
            [
                'nama_tag' => 'BMW',
                'tag_seo' => 'bmw',
                'count' => 0,
                'instansi_id' => 5,
            ],
            [
                'nama_tag' => 'Pengumuman',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 32,
            ],
            [
                'nama_tag' => 'Kategori Berita Pengumuman',
                'tag_seo' => 'kategori-berita-pengumuman',
                'count' => 0,
                'instansi_id' => 32,
            ],
            [
                'nama_tag' => 'Pengumuman',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 5,
            ],
            [
                'nama_tag' => 'Pembinaan',
                'tag_seo' => 'pembinaan',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Temu Lapang',
                'tag_seo' => 'temu-lapang',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Bantuan',
                'tag_seo' => 'bantuan',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Kunjungan',
                'tag_seo' => 'kunjungan',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Koordinasi',
                'tag_seo' => 'koordinasi',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Monitoring',
                'tag_seo' => 'monitoring',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Pengembangan dan Pengelolaan',
                'tag_seo' => 'pengembangan-dan-pengelolaan',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'PEMILIHAN KEPALA KAMPUNG DENTE MAKMUR 2019',
                'tag_seo' => 'pemilihan-kepala-kampung-dente-makmur-2019',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'USAHA EKONOMI PRODUKTIF(UEP) BERGERAK MELAYANI WARGA',
                'tag_seo' => 'usaha-ekonomi-produktifuep-bergerak-melayani-warga',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 53,
            ],
            [
                'nama_tag' => 'NASIONAL',
                'tag_seo' => 'nasional',
                'count' => 0,
                'instansi_id' => 53,
            ],
            [
                'nama_tag' => 'BANJAR AGUNG',
                'tag_seo' => 'banjar-agung',
                'count' => 0,
                'instansi_id' => 53,
            ],
            [
                'nama_tag' => 'Camat',
                'tag_seo' => 'camat',
                'count' => 0,
                'instansi_id' => 54,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 54,
            ],
            [
                'nama_tag' => 'Pemkab',
                'tag_seo' => 'pemkab',
                'count' => 0,
                'instansi_id' => 54,
            ],
            [
                'nama_tag' => 'kampung',
                'tag_seo' => 'kampung',
                'count' => 0,
                'instansi_id' => 54,
            ],
            [
                'nama_tag' => 'Banjar Baru',
                'tag_seo' => 'banjar-baru',
                'count' => 0,
                'instansi_id' => 54,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 63,
            ],
            [
                'nama_tag' => 'KECAMATAN PENAWAR AJI',
                'tag_seo' => 'kecamatan-penawar-aji',
                'count' => 0,
                'instansi_id' => 63,
            ],
            [
                'nama_tag' => 'KESENIAN',
                'tag_seo' => 'kesenian',
                'count' => 0,
                'instansi_id' => 63,
            ],
            [
                'nama_tag' => 'OLAHRAGA',
                'tag_seo' => 'olahraga',
                'count' => 0,
                'instansi_id' => 63,
            ],
            [
                'nama_tag' => 'PEMERINTAHAN',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 63,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'Kecamatan Menggala Timur',
                'tag_seo' => 'kecamatan-menggala-timur',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'Nasional',
                'tag_seo' => 'nasional',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'BMW',
                'tag_seo' => 'bmw',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'BMW',
                'tag_seo' => 'bmw',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Kecamatan Menggala',
                'tag_seo' => 'kecamatan-menggala',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Pemerintahan',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Kebudayaan dan Pariwisata',
                'tag_seo' => 'kebudayaan-dan-pariwisata',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Umum',
                'tag_seo' => 'Umum',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'Pemerintahan',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 44,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 44,
            ],
            [
                'nama_tag' => 'Bagian Tapem dan Otda',
                'tag_seo' => 'bagian-tapem-dan-otda',
                'count' => 0,
                'instansi_id' => 44,
            ],
            [
                'nama_tag' => 'MERAKSAAJI',
                'tag_seo' => 'meraksaaji',
                'count' => 0,
                'instansi_id' => 62,
            ],
            [
                'nama_tag' => 'PRESTASI',
                'tag_seo' => 'prestasi',
                'count' => 0,
                'instansi_id' => 62,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 56,
            ],
            [
                'nama_tag' => 'Umum',
                'tag_seo' => 'umum',
                'count' => 0,
                'instansi_id' => 56,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 0,
                'instansi_id' => 56,
            ],
            [
                'nama_tag' => 'Kebudayaan dan Pariwisata',
                'tag_seo' => 'kebudayaan-dan-pariwisata',
                'count' => 0,
                'instansi_id' => 56,
            ],
            [
                'nama_tag' => 'BERITA PENAWARTAMA',
                'tag_seo' => 'berita-penawartama',
                'count' => 0,
                'instansi_id' => 64,
            ],
            [
                'nama_tag' => 'Pemda Tulang Bawang',
                'tag_seo' => 'pemda-tulang-bawang',
                'count' => 0,
                'instansi_id' => 64,
            ],
            [
                'nama_tag' => 'PENGAWASAN',
                'tag_seo' => 'pengawasan',
                'count' => 0,
                'instansi_id' => 49,
            ],
            [
                'nama_tag' => 'KAPABILITAS APIP',
                'tag_seo' => 'kapabilitas-apip',
                'count' => 0,
                'instansi_id' => 49,
            ],
            [
                'nama_tag' => 'Berita Diperta',
                'tag_seo' => 'berita-diperta',
                'count' => 0,
                'instansi_id' => 5,
            ],
            [
                'nama_tag' => 'TulangBawang',
                'tag_seo' => 'tulangbawang',
                'count' => 0,
                'instansi_id' => 5,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'Bimbingan Teknis',
                'tag_seo' => 'bimbingan-teknis',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'PUSKESMAS RAWA JITU',
                'tag_seo' => 'puskesmas-rawa-jitu',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'SOP  MANUFACTURING & SERVICE DELIVERY',
                'tag_seo' => 'sop-manufacturing-service-delivery',
                'count' => 0,
                'instansi_id' => 7,
            ],
            [
                'nama_tag' => 'camat menggala',
                'tag_seo' => 'camat-menggala',
                'count' => 0,
                'instansi_id' => 60,
            ],
            [
                'nama_tag' => 'puprtulangbawang',
                'tag_seo' => 'puprtulangbawang',
                'count' => 0,
                'instansi_id' => 4,
            ],
            [
                'nama_tag' => 'LOMBA PERPUSTAKAAN DESA TK PROV LAMPUNG 2020',
                'tag_seo' => 'lomba-perpustakaan-desa-tk-prov-lampung-2020',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'Kejaksaan Negeri Tulang Bawang',
                'tag_seo' => 'kejaksaan-negeri-tulang-bawang',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'Ikatan Adhyaksa Dharmakarini Daerah Tulang Bawang',
                'tag_seo' => 'ikatan-adhyaksa-dharmakarini-daerah-tulang-bawang',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'Kampung Lebuh Dalem',
                'tag_seo' => 'kampung-lebuh-dalem',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'Kampung Cempaka Dalem',
                'tag_seo' => 'kampung-cempaka-dalem',
                'count' => 0,
                'instansi_id' => 61,
            ],
            [
                'nama_tag' => 'LOMBA BERCERITA SISWA SD/MI TINGKAT PROVINSI LAMPUNG 2020',
                'tag_seo' => 'lomba-bercerita-siswa-sdmi-tingkat-provinsi-lampung-2020',
                'count' => 0,
                'instansi_id' => 16,
            ],
            [
                'nama_tag' => 'DPRD Tulang Bawang',
                'tag_seo' => 'dprd-tulang-bawang',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Pendidikan',
                'tag_seo' => 'pendidikan',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Budaya',
                'tag_seo' => 'budaya',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Ekonomi',
                'tag_seo' => 'ekonomi',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Kesehatan',
                'tag_seo' => 'kesehatan',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Pariwisata',
                'tag_seo' => 'pariwisata',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Pemerintahan',
                'tag_seo' => 'pemerintahan',
                'count' => 0,
                'instansi_id' => 51,
            ],
            [
                'nama_tag' => 'Rehabilitasi',
                'tag_seo' => 'rehabilitasi',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Pengelola Pengadaan Barang & Jasa',
                'tag_seo' => 'pengelola-pengadaan-barang-jasa',
                'count' => 0,
                'instansi_id' => 50,
            ],
            [
                'nama_tag' => 'PUSKESMAS BANJAR BARU',
                'tag_seo' => 'puskesmas-banjar-baru',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'UPTD PUSKESMAS GEDUNG REJO SAKTI',
                'tag_seo' => 'uptd-puskesmas-gedung-rejo-sakti',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'Puskesmas Rawajitu Timur',
                'tag_seo' => 'puskesmas-rawajitu-timur',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'PUSKESMAS TULANG BAWANG I',
                'tag_seo' => 'puskesmas-tulang-bawang-i',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'PUSKESMAS GEDUNG MENENG',
                'tag_seo' => 'puskesmas-gedung-meneng',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'Puskesmas Way Dente',
                'tag_seo' => 'puskesmas-way-dente',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'SAKIP',
                'tag_seo' => 'sakip',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'PuskesmasTiuhTohou',
                'tag_seo' => 'puskesmastiuhtohou',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'PUSKESMAS RAWAT INAP RAWA PITU',
                'tag_seo' => 'puskesmas-rawat-inap-rawa-pitu',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'Puskesmas Makartitama',
                'tag_seo' => 'puskesmas-makartitama',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'puskesmas sidoharjo',
                'tag_seo' => 'puskesmas-sidoharjo',
                'count' => 0,
                'instansi_id' => 3,
            ],
            [
                'nama_tag' => 'Mentor',
                'tag_seo' => 'mentor',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Gotong Royong',
                'tag_seo' => 'gotong-royong',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Hari Kesaktian Pancasila',
                'tag_seo' => 'hari-kesaktian-pancasila',
                'count' => 0,
                'instansi_id' => 13,
            ],
            [
                'nama_tag' => 'Tulang Bawang',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 42,
            ],
            [
                'nama_tag' => 'Umum',
                'tag_seo' => 'umum',
                'count' => 0,
                'instansi_id' => 42,
            ],
            [
                'nama_tag' => 'MAL PELAYANAN PUBLIK',
                'tag_seo' => 'mal-pelayanan-publik',
                'count' => 0,
                'instansi_id' => 46,
            ],
            [
                'nama_tag' => 'PENGUMUMAN',
                'tag_seo' => 'pengumuman',
                'count' => 0,
                'instansi_id' => 46,
            ],
            [
                'nama_tag' => 'TULANG BAWANG',
                'tag_seo' => 'tulang-bawang',
                'count' => 0,
                'instansi_id' => 46,
            ],
            [
                'nama_tag' => 'LAMPUNG',
                'tag_seo' => 'lampung',
                'count' => 0,
                'instansi_id' => 46,
            ],
        ]);
    }
}