<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        DB::table('users')->insert([

            [
                'instansi_id' => 1,
                'name' => 'Disdik Kab. Tulang Bawang',
                'username' => 'Dinas Pendidikan',
                'email' => 'disdik@webservices.com',
                'address' => 'Jl. cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$6QGptFgJ79TONIfM3LfjG.xZwly.3h9c3pl22NSdyQBdV1RQOVHdK',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],

            [
                'instansi_id' => 2,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'sosial@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 3,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'dinkes@webservices.com',
                'address' => 'Jl. Cemara Kompleks Perkantoran Pemkab TUBA',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '082178907015',
                'password' => '$2y$10$RKqGPDPeR8/XxWsJ/p9Gh.HTlYXRqZyy5mHqp/P.8svzNQhcyUOFW',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 4,
                'name' => 'Dinas Pekerjaan Umum dan Penataan Ruang',
                'username' => 'admin',
                'email' => 'pupr@webservices.com',
                'address' => 'Jl. Cemara Lingkungan Gunung Sakti Kelurahan Menggala Selatan Kecamatan Menggala kabupaten Tulang bawang Provinsi lampung',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '072621186',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 5,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'pertanian@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 6,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'ekonomi@webservices.com',
                'address' => 'Jln.Cemara Lk.Gunung sakti Kel.Menggala Selatan kec.menggalakab.Tulang Bawang Provinsi Lampung Kode Pos : 34596',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '07267575177',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],

            [
                'instansi_id' => 7,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'kecapil@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 8,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'dkp@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 9,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'kominfo@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$7aVS2uGG.GTHfKW6fQCWaOFYdswYya27IOao9Q6beB9Plg/UtTNK6',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 10,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'koperasi@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 11,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'hidup@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 12,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'dishub@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 13,
                'name' => 'DINAS PERIKANAN KABUPATEN TULANG BAWANG',
                'username' => 'SANARIYAH, SH., M.M',
                'email' => 'perikanan@webservices.com',
                'address' => 'Jl. CEMARA GUNUNG SAKTI KOMPLEK PERKANTORAN PEMDA TUBA',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '081369378972',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 14,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'perdagangan@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 15,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'perkebunan@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 16,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'arsip@webservices.com',
                'address' => 'Jl. 1 Ujung Gunung Kec.Menggala',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '-',
                'password' => '$2y$10$8kCGQjInhkGD9B4XuG/OkuIv1N/u5FJ0mm8cnqLCtgJ/VtyQGPkbC',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 17,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'pmk@webservices.com',
                'address' => 'Jl.Lintas Timur KM 112 Tiuh Tohou Kecamatan Menggala Kabupaten Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '(0726)7575380',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 18,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'pmptsp@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 19,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'diskepora@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 20,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'dppkb@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 21,
                'name' => 'admin',
                'username' => 'menggalakota001',
                'email' => 'transmigrasi@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 22,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'tphp@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 23,
                'name' => 'SATUAN POLISI PAMONG PRAJA',
                'username' => 'SATUAN POLISI PAMONG PRAJA',
                'email' => 'polpp@webservices.com',
                'address' => 'Jl. cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '082281845915',
                'password' => '$2y$10$1SyfaRhE5UxdYm8/H0jbGOX8A4H18EItXbrBP4u2Gb1UQjwoXY0ma',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 24,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bpbd@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 25,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'kesrak@webservices.com',
                'address' => 'Jl. Cemara Gunung Sakti Komplek Perkantoran Pemda Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 26,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'kesbangpol@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 27,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'sekdak@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 28,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'kecamatan@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 29,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'tatpem@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 30,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bkpp@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 31,
                'name' => 'tomi',
                'username' => 'bpkad1',
                'email' => 'bpkadtuba@webservices.com',
                'address' => 'Jalan Negara Lintas Timur KM 112 Tiuh Tohou Kabupaten Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$CN0rSB6B/y7PWlfvBqpCtuODbqjrY.8ETo6G7Pz8T2R4vDAab7d9y',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 32,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bppd@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 33,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bpd@webservices.com',
                'address' => 'Jl. Cemara Komplek Perkantoran Pemda, Kel. Menggala Selatan, Kec. Menggala, Kab. Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 43,
                'name' => 'DINAS PARIWISATA DAN KEBUDAYAAN',
                'username' => 'admin',
                'email' => 'disparbud@webservices.com',
                'address' => 'Jalan Cemara Komplek Perkantoran Pemda Tulang Bawang, Menggala.',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 41,
                'name' => 'Bayu Eko Heriawan',
                'username' => 'admin',
                'email' => 'dp3a@webservices.com',
                'address' => 'Jalan Lintas Timur Sumatera KM 120 Kec.Menggala Kab.Tulang Bawang Provinsi Lampung',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 42,
                'name' => 'DINAS PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN',
                'username' => 'NADIANSYAH FS',
                'email' => 'dprkp@webservices.com',
                'address' => 'Jl. Cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '09127946145',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 36,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'baghukum@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 37,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bagsda@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 44,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bagotonomi@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 38,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bagor@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 39,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bagprotokol@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 40,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'bagkeu@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 10,
                'name' => 'Fasrie',
                'username' => 'Fasrie',
                'email' => 'fasrie108@gmail.com',
                'address' => 'U2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '081369332999',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
            ],
            [
                'instansi_id' => 32,
                'name' => 'Sarkis Enda Raya Simanjuntak',
                'username' => 'simanjuntaksarkis@gmail.com',
                'email' => 'simanjuntaksarkis@gmail.com',
                'address' => 'Rajabasa',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '082176151471',
                'password' => '$2y$10$.nOCp..czerwYJwXgd6wu.hSheGJxQMZPqQzOw3hzhMMWzkzklnbq',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 12,
                'name' => 'Mualif',
                'username' => 'diperhub123',
                'email' => 'dishub@gmail.com',
                'address' => 'jl raden intan',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '08xxxxx',
                'password' => '$2y$10$cSyCk8bwIrfgWU5cS15dSe54cxzt0v5Ub5xFzSD9hzvLie1FU/cB2',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 9,
                'name' => 'PRAMADYA,SKM., M.Kes.',
                'username' => 'Admin',
                'email' => 'pramadya_ku@yahoo.co.id',
                'address' => 'Jl. Cemara No. 1 Menggala Komplek Perkantoran Pemkab Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '08127209961',
                'password' => '$2y$10$sWnnmqjGbmXiu6/BzsfO6e/Vcvpjk.UarjvQmmdemmmNmASORtSlK',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 9,
                'name' => 'toni',
                'username' => 'admin',
                'email' => 'fahnaf007@gmail.com',
                'address' => 'Jl Cemara No 1 Menggala Komplek Pemda Tuba',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '082177297739',
                'password' => '$2y$10$oIcYWtQdUD6vhEyZmUpVauXBmNRQHmdieXdyTSe42msnj9L7cG1UK',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 45,
                'name' => 'Bagian Umum',
                'username' => 'admin',
                'email' => 'bagumum@webservices.com',
                'address' => 'Jl. Cemara Komplek Pemda Tulang Bawang',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '7575156',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 46,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'mpp@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 47,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'rsud@webservices.com',
                'address' => 'Jl. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 49,
                'name' => 'admin',
                'username' => 'admin',
                'email' => 'inspektorat@webservices.com',
                'address' => 'l. Kenangan 2',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                    'instansi_id' => 47,
                    'name' => 'adisuma',
                    'username' => 'adisuma',
                    'email' => 'adisuma@webservices.com',
                    'address' => 'rsud menggala',
                    'email_verified_at' => NULL,
                    'hak_akses' => 'super admin',
                    'phone' => '009',
                    'password' => '$2y$10$8anR0k9jjqUyCLxaEGqzJuayHzyXQub8I4fXda8Sz78m.7zVwbORe',
                    'remember_token' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ],
                [
                    'instansi_id' => 50,
                    'name' => 'Bagian Pengadaan Barang dan Jasa Kab. Tulang Bawang',
                    'username' => 'Bagian Pengadaan Barang dan Jasa',
                    'email' => 'bpbj@webservices.com',
                    'address' => 'Jl. cemara komplek perkantoran pemda',
                    'email_verified_at' => NULL,
                    'hak_akses' => 'super admin',
                    'phone' => '0702101',
                    'password' => '$2y$10$FmklyM7E7sLcLn9dfzRJvux8MRQX9LeX04ZK55XAms79Abf5vhkGS',
                    'remember_token' => NULL,
                    'created_at' => '2019-03-20 01:53:33',
                    'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 51,
                'name' => 'Kepala Dewan',
                'username' => 'dewanperwakilanrakyat',
                'email' => 'dprd@webservices.com',
                'address' => 'Jl. cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 1,
                'name' => 'Microdata',
                'username' => 'Microdata',
                'email' => 'xxax@webservices.com',
                'address' => 'l. cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 01:53:33',
                'updated_at' => '2019-03-20 01:53:33',
                ],
                [
                'instansi_id' => 47,
                'name' => 'henricus',
                'username' => 'henricus',
                'email' => 'henricus@webservices.com',
                'address' => 'henricus',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => 'henricus',
                'password' => '$2y$10$.Eq2FNwdtAyYOAs9ZgCpMuuQeUfvPeH5RLhf2aEksWB2qdlv5K1xC',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 10,
                'name' => 'WisnuKu',
                'username' => 'WisnuKu',
                'email' => 'wisnuku10@gmail.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$vcjopR12vRq65kCRa8nmz.iRrsreB8UBje/wlkvUzRDY1Gkk58fr.',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 50,
                'name' => 'SUFRIYADI',
                'username' => 'aceng',
                'email' => 'aceng_sufriyadi@yahoo.co.id',
                'address' => 'BAGIAN PENGADAAN BARANG DAN JASA',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$rTX7BwapWTRrOYpz0w/up.e1WeRlTszHfwMYiuQeTjXsjW/O.OVya',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 50,
                'name' => 'fadry',
                'username' => 'fadry',
                'email' => 'aa@Wdd.com',
                'address' => 'aa',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '11',
                'password' => '$2y$10$37gRPs7lhmYVSJoKj67V9OnJsDxEmKpqot909/331VwaCdP3owKVK',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 52,
                'name' => 'Kepala Sekretariat',
                'username' => 'setkorpri',
                'email' => 'setkorpri@webservices.com',
                'address' => 'Jl. cemara komplek perkantoran pemda',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '0702101',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => '2019-03-20 08:53:33',
                'updated_at' => '2019-03-20 08:53:33',
                ],
                [
                'instansi_id' => 53,
                'name' => 'Banjar Agung',
                'username' => 'Banjar Agung',
                'email' => 'banjaragung@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$21elBcTXHjbaH/b57yuEFOp8IpvA5ZayYcgo3ieiTI6V2DvH9Gumy',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 54,
                'name' => 'Banjar Baru',
                'username' => 'Banjar Baru',
                'email' => 'banjarbaru@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 55,
                'name' => 'Banjar Margo',
                'username' => 'Banjar Margo',
                'email' => 'banjarmargo@webservices.com',
                'address' => 'Jl.Pagar Alam  Kamp. Agung Dalam',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 56,
                'name' => 'Dente Teladas',
                'username' => 'Dente Teladas',
                'email' => 'denteteladas@webservices.com',
                'address' => 'Jl. Poros Kampung Way Dente Kampung Way Dente Kode Pos 34596',
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => '081366462306',
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 57,
                'name' => 'Gedung Aji',
                'username' => 'Gedung Aji',
                'email' => 'gedungaji@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 58,
                'name' => 'Gedung Aji Baru',
                'username' => 'Gedung Aji Baru',
                'email' => 'gedungajibaru@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 59,
                'name' => 'Gedung Meneng',
                'username' => 'Gedung Meneng',
                'email' => 'gedungmeneng@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 60,
                'name' => 'Menggala',
                'username' => 'Menggala',
                'email' => 'menggala@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 61,
                'name' => 'Menggala Timur',
                'username' => 'Menggala Timur',
                'email' => 'menggalatimur@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 62,
                'name' => 'Meraksa Aji',
                'username' => 'Meraksa Aji',
                'email' => 'meraksaaji@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 63,
                'name' => 'Penawar Aji',
                'username' => 'Penawar Aji',
                'email' => 'penawaraji@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 64,
                'name' => 'Penawar Tama',
                'username' => 'Penawar Tama',
                'email' => 'penawartama@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 65,
                'name' => 'Rawa Jitu Selatan',
                'username' => 'Rawa Jitu Selatan',
                'email' => 'rawajituselatan@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 66,
                'name' => 'Rawa Jitu Timur',
                'username' => 'Rawa Jitu Timur',
                'email' => 'rawajitutimur@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 67,
                'name' => 'Rawa Pitu',
                'username' => 'Rawa Pitu',
                'email' => 'rawapitu@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 68,
                'name' => 'Kejaksaan Negeri',
                'username' => 'Kejaksaan Negeri',
                'email' => 'kejari@webservices.com',
                'address' => NULL,
                'email_verified_at' => NULL,
                'hak_akses' => 'super admin',
                'phone' => NULL,
                'password' => '$2y$10$/ZLE/o56k51PaLJs7cAO8.jFmTzBEsBGtKW6EG/j3yz5jlBG/XsSe',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'ALFA SUKMAWATI',
                'username' => 'pkm.paduanrajawali89@gmail.com',
                'email' => 'pkm.paduanrajawali89@gmail.com',
                'address' => 'Puskesmas Paduan Rajawali',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0823 7917 372',
                'password' => '$2y$10$dWWPNsb5mrOheFzUcp2Zve5MVC.hD/nQL2pZotv3g1CQ5lxJ.q9yK',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'REKA ANISTA',
                'username' => 'rawapitupuskesmas@gmail.com',
                'email' => 'rawapitupuskesmas@gmail.com',
                'address' => 'Puskesmas Rawa Pitu',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0878 9300 821',
                'password' => '$2y$10$V9WJytv80tGRPfAuMVtzguyHR7d2K/fn36vUGpVIMwRDTfBDdUnHS',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'FELLISIYAH KUSUMA WATI',
                'username' => 'pkm.rawajitu@gmail.com',
                'email' => 'pkm.rawajitu@gmail.com',
                'address' => 'Puskesmas Rawa Jitu',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0813 1882 040',
                'password' => '$2y$10$IELBiAZfcHHFBhlgAAqW/uZiPoqp4kYj10l.c85Ix3l8QZIusEo6y',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'RILO SAYEKTI',
                'username' => 'pkmtubasatu@yahoo.com',
                'email' => 'pkmtubasatu@yahoo.com',
                'address' => 'Puskesmas Tulang Bawang I',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0812 7919 800',
                'password' => '$2y$10$aQV748qqu1G0WrFeiHtrae4EFq1yWLr9i6BW1p/VmHSJOyRzyF.8S',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'WIDYA RESMIWATI PUTRI',
                'username' => 'Pkm_gedungaji@yahoo.co.id',
                'email' => 'Pkm_gedungaji@yahoo.co.id',
                'address' => 'Puskesmas Gedung Aji',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '852 6754 3676',
                'password' => '$2y$10$fs3Ta4J8OGEDuvD30QC3fevC/FnRW3z32c.fzmjbOegr.aKX7lBJ2',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'JERRY SETIAWAN',
                'username' => 'pkm24gedungkaryajitu@gmail.com',
                'email' => 'pkm24gedungkaryajitu@gmail.com',
                'address' => 'Puskesmas Gedung Karya Jitu',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0822 8265 352',
                'password' => '$2y$10$g13AVVyEUtpI8eVpF/pU/.2CFjL9e7IRgNMHfN4p2/0ZYSHstxpoy',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'SUCI ANANDA FEBRIYANTI',
                'username' => 'pkmpenawarjaya@gmail.com',
                'email' => 'pkmpenawarjaya@gmail.com',
                'address' => 'Puskesmas Penawar Jaya',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0813 7779 852',
                'password' => '$2y$10$yofLYYxk5euQJi/zLLGb7OZE5t2gACmJULusMo4s0baSzQVdTCOSq',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'DWI APRIYANI',
                'username' => 'puskesmassidoharjo@gmail.com',
                'email' => 'puskesmassidoharjo@gmail.com',
                'address' => 'Puskesmas Sidoharjo',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0856 4011 806',
                'password' => '$2y$10$HgqBYAjff0.D/KdHsS1lAemzPATOfRX37/VYwn68ip7A6SfmoyUEy',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
                [
                'instansi_id' => 3,
                'name' => 'RIMAWATI',
                'username' => 'puskesmaspenawaraji@gmail.com',
                'email' => 'puskesmaspenawaraji@gmail.com',
                'address' => 'Puskesmas Gedung Rejo Sakti',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0822 8905 861',
                'password' => '$2y$10$6e9f/tBAQIphs.MDZMD42.TcRyzHpM1X77nyJlde2Sh2M8aZ1Ce02',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                ],
            [
                'instansi_id' => 3,
                'name' => 'RAMA RISKI PUTRA',
                'username' => 'puskesmasmenggala14@gmail.com',
                'email' => 'puskesmasmenggala14@gmail.com',
                'address' => 'Puskesmas Menggala',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '082180201919',
                'password' => '$2y$10$7y9.7YEfbXJ7geZ2HkW3Jua0/opy0AY16CmV3HC5kosAbkKTuQ/7m',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'IKA APRI ROMAYANTI',
                'username' => 'puskesmaspasiranjaya@gmail.com',
                'email' => 'puskesmaspasiranjaya@gmail.com',
                'address' => 'Puskesmas Pasiran Jaya',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0822 8119 727',
                'password' => '$2y$10$JQX9pZWr30eel8mt50O.eOsDJicq51YoV92HPCD5OaexyS8cqL/WG',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'UMI RAHMAWATI',
                'username' => 'makartitama_keren@yahoo.com',
                'email' => 'makartitama_keren@yahoo.com',
                'address' => 'Puskesmas Makartitama',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0812 4902 539',
                'password' => '$2y$10$gdO70f3RqtObcUFCY7SS3u5weqt6cIJcuCliXKbCJJ1PQ5xd3Vj5S',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'WIHARI SIGIT SASONGKO',
                'username' => 'banjarbarupuskesmas@gmail.com',
                'email' => 'banjarbarupuskesmas@gmail.com',
                'address' => 'Puskesmas Banjar Baru',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0822 2316 538',
                'password' => '$2y$10$wdmP1Xb5AzSr3jtgSKbhd.2qN0CR/8Bs7VQBkg6cZcVab.XiJ.Hru',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'ANITA',
                'username' => 'pkmrjt@gmail.com',
                'email' => 'pkmrjt@gmail.com',
                'address' => 'Puskesmas rawa Jitu Timur',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0823 7898 702',
                'password' => '$2y$10$JicyA7S31Pfe1E9kxxoQb.e/qJrHLw5htxmU0QJDKW4gCW.J31myq',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'AJENG VIONI PUTRI',
                'username' => 'pkmwaydente@gmail.com',
                'email' => 'pkmwaydente@gmail.com',
                'address' => 'Puskesmas Way Dente',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0812 7328 666',
                'password' => '$2y$10$R6.vPXN.WJu/bOwibiKpceb1FBwhroe5wPSEZGRB9ePTpIye6c4Pq',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'ANNISA AMALIA RIZALDI',
                'username' => 'puskesmasgedungmeneng2017@gmail.com',
                'email' => 'puskesmasgedungmeneng2017@gmail.com',
                'address' => 'Puskesmas Gedung Meneng',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '0812 2118 845',
                'password' => '$2y$10$oL2jd92kgf2FIpD/u2Ny4.ShrNK3fJNdPIpvOJwelirseUHjGLMsC',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'instansi_id' => 3,
                'name' => 'NIARA ORCHA THISTANIA',
                'username' => 'pkmtito@gmail.com',
                'email' => 'pkmtito@gmail.com',
                'address' => 'Puskesmas Tiuh Toho',
                'email_verified_at' => NULL,
                'hak_akses' => 'admin view',
                'phone' => '081525744808',
                'password' => '$2y$10$EunJAFRLxTDOpWPN84v8..0GSPnosWCdY4eYqoCJwe1V9tQ93RVau',
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);
    }
}